spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306
    username: root
    password: 1234

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 28080

toss:
  secret-key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
  url: https://api.tosspayments.com